# Default values for nginx-sample-chart.
replicaCount: 2
image:
  repository: invisiblelad/app
<<<<<<< Updated upstream
  tag: 81759b0
=======
  tag: afcae04
>>>>>>> Stashed changes
resources:
  limits:
    memory: "125Mi"
    cpu: "500m"
container:
  port: 5000
service:
  type: ClusterIP
  port: 80
  targetPort: 5000

