# Default values for nginx-sample-chart.
replicaCount: 2
image:
  repository: invisiblelad/app
  tag: ec1440e
resources:
  limits:
    memory: "125Mi"
    cpu: "500m"
container:
  port: 5000
service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

