# Default values for nginx-sample-chart.
replicaCount: 2
image:
  repository: invisiblelad/app
  tag: 343eae5
resources:
  limits:
    memory: "125Mi"
    cpu: "500m"
service:
  type: ClusterIP
  port: 80

