# Default values for nginx-sample-chart.
replicaCount: 2
image:
  repository: app
<<<<<<< Updated upstream
  tag: b3a147b
=======
  tag: aee16cf
>>>>>>> Stashed changes
resources:
  limits:
    memory: "150Mi"
    cpu: "500m"
service:
  type: ClusterIP
  port: 80

