# Default values for nginx-sample-chart.
replicaCount: 2
image:
  repository: app
<<<<<<< Updated upstream
  tag: 065daa2
=======
<<<<<<< Updated upstream
  tag: a9626db
=======
<<<<<<< Updated upstream
  tag: a9626db
=======
  tag: a9626db
>>>>>>> Stashed changes
>>>>>>> Stashed changes
>>>>>>> Stashed changes
resources:
  limits:
    memory: "150Mi"
    cpu: "500m"
service:
  type: ClusterIP
  port: 80

